name: Run Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        run: |
          # 필요한 환경 설정을 여기에 추가하세요

      - name: Make runserver.sh executable
        run: chmod +x runserver.sh

      - name: Run server
        run: ./runserver.sh