name: Android Test Workflow

on:
  workflow_dispatch:

jobs:
  android_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: 환경 설정 확인
        run: |
          echo "Node 버전: $(node --version)"
          echo "npm 버전: $(npm --version)"
          echo "Appium 버전: $(appium --version)"
          echo "ADB 버전: $(adb version)"

      - name: Appium 서버 시작
        run: |
          appium --address 0.0.0.0 --port 4723 &
          sleep 10
          if nc -z localhost 4723; then
            echo "Appium 서버가 실행 중입니다."
          else
            echo "Appium 서버 시작 실패"
            exit 1
          fi

      - name: 안드로이드 기기 연결 확인
        run: |
          devices=$(adb devices | grep -v "List" | grep "device$")
          if [ -n "$devices" ]; then
            echo "연결된 기기:"
            echo "$devices"
          else
            echo "연결된 안드로이드 기기가 없습니다."
            exit 1
          fi

      - name: 안드로이드 테스트 실행
        run: |
          ./gradlew connectedAndroidTest

      - name: 테스트 결과 업로드
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: '**/build/reports/androidTests'