name: TestWorkflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '테스트할 브랜치'
        required: true
        default: 'main'
      test_scope:
        description: '테스트 범위'
        required: true
        type: choice
        options:
          - folder
          - class
          - method
      test_domain:
        description: '테스트할 도메인 (예: AndroidTest)'
        required: true
        default: 'AndroidTest'

jobs:
  android_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Gradle 캐시
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Appium 서버 상태 확인 및 시작
        run: |
          if ! pgrep -x "appium" > /dev/null
          then
            echo "Appium 서버가 실행 중이 아닙니다. 시작합니다."
            appium &
            sleep 10  # Appium 서버가 완전히 시작될 때까지 대기
          else
            echo "Appium 서버가 이미 실행 중입니다."
          fi

      - name: 에뮬레이터 상태 확인
        run: |
          if adb devices | grep -q "emulator"; then
            echo "에뮬레이터가 이미 실행 중입니다."
          else
            echo "에뮬레이터가 실행되고 있지 않습니다. 에뮬레이터를 시작해주세요."
            exit 1
          fi

      - name: 테스트 실행
        run: |
          if [ "${{ github.event.inputs.test_scope }}" = "all" ] || [ "${{ github.event.inputs.test_scope }}" = "unit" ]; then
            ./gradlew test --tests "${{ github.event.inputs.test_domain }}*"
          fi
          if [ "${{ github.event.inputs.test_scope }}" = "all" ] || [ "${{ github.event.inputs.test_scope }}" = "instrumented" ]; then
            ./gradlew connectedAndroidTest --tests "${{ github.event.inputs.test_domain }}*"
          fi

      - name: 테스트 결과 업로드
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: '**/build/test-results'