name: TestWorkflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '테스트할 브랜치'
        required: true
        default: 'main'
      test_scope:
        description: '테스트 범위'
        required: true
        type: choice
        options:
          - folder
          - class
          - method
      test_target:
        description: '테스트 대상 (폴더/클래스/메소드 이름)'
        required: true
        default: 'AndroidTest'

jobs:
  android_test:
    runs-on: self-hosted  # 여기를 self-hosted로 변경
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Appium 서버 상태 확인
        run: |
          if pgrep -x "appium" > /dev/null; then
            echo "Appium 서버가 실행 중입니다."
          else
            echo "Appium 서버가 실행되고 있지 않습니다. Appium을 시작합니다."
            appium &
            sleep 10
          fi

      - name: 실제 디바이스 연결 확인
        run: |
          devices=$(adb devices | grep -v "List" | grep "device$")
          if [ -n "$devices" ]; then
            echo "연결된 디바이스:"
            echo "$devices"
          else
            echo "연결된 디바이스가 없습니다. 디바이스를 연결해주세요."
            exit 1
          fi

      - name: 테스트 실행
        run: |
          if [ "${{ github.event.inputs.test_scope }}" = "folder" ]; then
            ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.package=${{ github.event.inputs.test_target }}
          elif [ "${{ github.event.inputs.test_scope }}" = "class" ]; then
            ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=${{ github.event.inputs.test_target }}
          elif [ "${{ github.event.inputs.test_scope }}" = "method" ]; then
            ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=${{ github.event.inputs.test_target }}#${{ github.event.inputs.test_target }}
          else
            echo "잘못된 테스트 범위입니다."
            exit 1
          fi

      - name: 테스트 결과 업로드
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: '**/build/test-results'